#!/bin/bash
alias ga='git add .'
alias gauto='git add . && git commit -m "Backup" && git push origin HEAD'
alias gb='git branch'
alias gc='git commit -m'
alias gph='git push origin'
alias gpl='git pull origin'
alias gs='git status'
alias gsw='git switch'
alias gd='git diff'
alias glog='git log --oneline -n 20'
